import Head from 'next/head';

export default function Home() {
  try {
    fetch('http://localhost:3000/api/products')
      .then((res) => res.json())
      .then((data) => console.log(data));
  } catch (error) {
    console.log(error);
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>Hello World</h1>
      </main>
    </div>
  );
}
export async function getServerSideProps() {
  return {
    props: {}, 
  };
}
